---
- name: Ensure headless java is installed
  ansible.builtin.dnf:
    name: java-17-openjdk-headless
    state: present

- name: Generate keystore
  when:
    - generate_keystore | bool
  community.general.java_keystore:
    name: "{{ instance_name }}"
    certificate_path: "{{ cert_pkcs12_path }}"
    private_key_path: "{{ private_key_path }}"
    password: "{{ keystore_password }}"
    dest: "{{ keystore_path }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_user }}"