- name: Ensure python cryptography libraries are installed
  ansible.builtin.dnf:
    name: python3-cryptography
    state: present

- name: Generate Private Key
  community.crypto.openssl_privatekey:
    path: "{{ private_key_path }}"
    size: "{{ private_key_bits }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_user }}"
    mode: 0600

- name: Generate an OpenSSL public key in PEM format
  community.crypto.openssl_publickey:
    path: "{{ public_key_path }}"
    privatekey_path: "{{ private_key_path }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_user }}"

- name: Generate the CSR
  community.crypto.openssl_csr:
    path: "{{ csr_path }}"
    privatekey_path: "{{ private_key_path }}"
    use_common_name_for_san: false
    common_name: "{{ cert_common_name }}"
    digest: "{{ cert_digest }}"
    country_name: "{{ cert_country }}"
    state_or_province_name: "{{ cert_state }}"
    locality_name: "{{ cert_locality }}"
    organization_name: "{{ cert_organization }}"
    organizational_unit_name: "{{ cert_ou }}"
    email_address: "{{ cert_email }}"
    subject_alt_name: "{{
      (cert_dns_sans | map('regex_replace', '^', 'DNS:') | list) +
      (cert_ip_sans | map('regex_replace', '^', 'IP:') | list)
    }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_user }}"

- name: Generate a Self Signed OpenSSL certificate
  notify: nexus_restart
  community.crypto.x509_certificate:
    path: "{{ cert_path }}"
    privatekey_path: "{{ private_key_path }}"
    csr_path: "{{ csr_path }}"
    provider: selfsigned

- name: Generate PKCS#12 file
  community.crypto.openssl_pkcs12:
    action: export
    path: "{{ cert_pkcs12_path }}"
    friendly_name: "{{ instance_name }}"
    privatekey_path: "{{ private_key_path }}"
    certificate_path: "{{ cert_path }}"
    state: present