---
instance_name: nexus
nexus_base_dir: /opt/sonatype
application_port: 8080
application_port_ssl: 8443
keystore_password: changeme
trust_store_password: changeme
nexus_jvm_xms_mbytes: 8192
nexus_jvm_xmx_mbytes: 8192

setup_certs: true
self_signed: true
private_key_bits: 4096
private_key_path: "{{ nexus_base_dir }}/nexus/etc/ssl/{{ instance_name }}.key"
public_key_path: "{{ nexus_base_dir }}/nexus/etc/ssl/{{ instance_name }}.pub"
csr_path: "{{ nexus_base_dir }}/nexus/etc/ssl/{{ instance_name }}.csr"
cert_path: "{{ nexus_base_dir }}/nexus/etc/ssl/{{ instance_name }}.crt"
keystore_path: "{{ nexus_base_dir }}/nexus/etc/ssl/keystore.jks"
keystore_pass: changeme


cert_common_name: "{{ instance_name }}"
cert_digest: sha256
cert_country: US
cert_state: ny
cert_locality: manhattan
cert_organization: "ACME org"
cert_ou: "Webmasters"
cert_email: "webmaster@example.com"
cert_dns_sans:
  - maven.example.com
  - nexus.example.com
cert_ip_sans:
  - 1.2.3.4
  - 5.6.7.8
combined_san: >-
  {{
    cert_dns_sans | map('regex_replace', '^(.*)$', 'DNS:\\1') | list
    + cert_ip_sans | map('regex_replace', '^(.*)$', 'IP:\\1') | list
  }}
