---
- name: Ensure config files are correct
  loop:
    - src: templates/nexus.properties.j2
      dest: "{{ nexus_base_dir }}/etc/nexus.properties"
    - src: templates/jetty-https.xml.j2
      dest: "{{ nexus_base_dir }}/etc/jetty/jetty-https.xml"
    - src: templates/nexus.vmoptions.j2
      dest: "{{ nexus_base_dir }}/bin/nexus.vmoptions"
    - src: templates/nexus.service.j2
      dest: "/etc/systemd/system/nexus.service"
  notify: nexus_restart
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_user }}"
    backup: true

- name: Setup certs
  when: setup_certs | bool
  notify: nexus_restart
  ansible.builtin.include_tasks:
    file: cert_setup.yml

- name: Ensure nexus service is started and enabled
  ansible.builtin.service:
    name: nexus
    state: started
    enabled: true
